name: "Bug report"
description: Report an issue with ArcGIS REST JS
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please include a clear and concise description of the bug. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a public repository, codepen, or jsbin (you can start with https://codepen.io/pen?template=YzpGqep) that reproduces the issue, along with a step by step explanation of how to see the issue. If no reproduction case is provided within a reasonable time-frame, the issue will be closed.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please include browser console around the time this bug occurred. Please try not to insert an image but copy paste the log text."
      render: shell
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please include which version of ArcGIS REST JS you are using and the output of `npx envinfo --system --binaries --browsers --npmPackages "{@esri/arcgis-rest-request,@esri/arcgis-rest-feature-service,@esri/arcgis-rest-geocoding,@esri/arcgis-rest-routing,@esri/arcgis-rest-demographics,@esri/arcgis-rest-portal}"`
      render: shell
      placeholder: "ArcGIS REST JS version: `v_._._`"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
