name: Deploy Documentation

# After a push to master, redeploy the docs
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: NPM Install
        run: npm install

      - name: Build Packages
        run: npm run build

      - name: Build Docs
        run: npm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build # The folder the action should deploy.
